version: "3"
services:
  hash_playground:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: hash_playground-image
    container_name: hash_playground-container
    tty: true
